### ISSUE TITLE
Eval in main class

### ISSUE THREAD

**Issue by SOF3** [UIPlugins/EvalUI#1]
This makes `$this` more meaningful.
By the way, what is wrong with using `onCommand` 🙈

**Comment by artulloss** [comment]
Nothing's wrong with it I just prefer extending a class because OOP isn't Pocketmine specific, and using plugin.yml is. I get that it can lead to more boilerplate but you can also do some useful things by structuring your commands as such since it gives you more flexibility in the long run, but yea for something as small as this, that's fine. I guess in the end it's just down to preference.

**Comment by SOF3** [comment]
Well yeah, in the long run. A simple eval plugin in the long run. You're gonna add a thousand commands to this plugin. What a nice idea.

**Comment by artulloss** [comment]
> I just prefer extending a class because OOP isn't Pocketmine specific, and using plugin.yml is

**Comment by SOF3** [comment]
This issue isn't about whether you create a class only for the command. It is about running the `eval()` function in the main class context, which does not stop you from creating a hundred other classes in the inheritance chain to create a simple command.

**Comment by artulloss** [comment]
Oh, so you'd like me to make it so they can access the main class easier via command, sure, I'll do that.

**Comment by artulloss** [comment]
fixed

**Comment by SOF3** [comment]
"The only variables defined are $server and $sender which both should work exactly as expected." needs to be updated.

**Comment by Aericio** [comment]
also fix formatting lol

**Comment by artulloss** [comment]
I don't really understand how to format it properly, if you'd like to fix it go ahead, I'll take care of fixing the readme later today.

**Comment by artulloss** [comment]
I think this is pretty much resolved, closing.
